# Generated by Django 3.0.2 on 2020-01-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20200128_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_title', models.TextField()),
                ('cat_description', models.TextField()),
                ('cat_collapsed', models.BooleanField(default=True)),
                ('cat_created', models.DateTimeField(auto_now_add=True)),
                ('cat_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Users')),
            ],
        ),
    ]
