# Generated by Django 3.0.2 on 2020-01-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200128_0837'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_title', models.TextField()),
                ('post_description', models.TextField()),
                ('post_likes', models.IntegerField(default=0)),
                ('post_dislikes', models.IntegerField(default=0)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_edited', models.DateTimeField(null=True)),
                ('post_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Users')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='cat_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Category'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='post_categories',
        ),
        migrations.CreateModel(
            name='PostsInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_liked', models.BooleanField(default=False, null=True)),
                ('post_disliked', models.BooleanField(default=False, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Users')),
            ],
            options={
                'db_table': 'post_interactions',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='post_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Category'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_message', models.TextField()),
                ('comment_likes', models.BigIntegerField(default=0, null=True)),
                ('comment_dislikes', models.BigIntegerField(default=0, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_editdate', models.DateTimeField(null=True)),
                ('commentor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Users')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Posts')),
            ],
            options={
                'db_table': 'post_comments',
            },
        ),
    ]
