# Generated by Django 3.0.2 on 2020-01-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200128_0837'),
        ('posts', '0002_auto_20200128_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsinteractions',
            name='post_interactdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='CommentInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_liked', models.BooleanField(default=False, null=True)),
                ('comment_disliked', models.BooleanField(default=False, null=True)),
                ('comment_interactdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Comments')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Users')),
            ],
            options={
                'db_table': 'comment_interactions',
            },
        ),
    ]
