# Generated by Django 3.0.2 on 2020-01-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=65, unique=True)),
                ('user_password', models.CharField(max_length=65)),
                ('user_email', models.CharField(max_length=65)),
                ('user_pin', models.CharField(max_length=16)),
                ('user_registered', models.DateTimeField(auto_now_add=True)),
                ('user_logged_in', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
    ]
