# Generated by Django 3.0.2 on 2020-01-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_fname', models.CharField(max_length=65)),
                ('profile_mname', models.CharField(max_length=65)),
                ('profile_lname', models.CharField(max_length=65)),
                ('profile_bday', models.DateField(null=True)),
                ('profile_address', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='user_confkey',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
