# Generated by Django 3.0.2 on 2020-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200128_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
