# Generated by Django 3.0.2 on 2020-01-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200128_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('char_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='users.Users')),
                ('char_money', models.IntegerField(default=100)),
                ('char_kills', models.IntegerField(default=0)),
                ('char_deaths', models.IntegerField(default=0)),
                ('char_x', models.FloatField(max_length=[16, 5])),
            ],
        ),
    ]
