# Generated by Django 3.0.2 on 2020-01-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_characters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'managed': False},
        ),
    ]
