# Generated by Django 3.0.2 on 2020-01-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20200128_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=65)),
                ('group_description', models.TextField()),
                ('group_editusers', models.BooleanField(default=False)),
                ('group_deleteusers', models.BooleanField(default=False)),
                ('group_addusers', models.BooleanField(default=False)),
                ('group_addgroups', models.BooleanField(default=False)),
                ('group_addusergroup', models.BooleanField(default=False)),
                ('group_removeusergroup', models.BooleanField(default=False)),
                ('group_editgroups', models.BooleanField(default=False)),
                ('group_removegroups', models.BooleanField(default=False)),
                ('group_editposts', models.BooleanField(default=False)),
                ('group_removeposts', models.BooleanField(default=False)),
                ('group_banuser', models.BooleanField(default=False)),
                ('group_timebanuser', models.BooleanField(default=False)),
                ('group_unbanuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='users.Users')),
                ('user_editusers', models.BooleanField(default=False)),
                ('user_deleteusers', models.BooleanField(default=False)),
                ('user_addusers', models.BooleanField(default=False)),
                ('user_addgroups', models.BooleanField(default=False)),
                ('user_addusergroup', models.BooleanField(default=False)),
                ('user_removeusergroup', models.BooleanField(default=False)),
                ('user_editgroups', models.BooleanField(default=False)),
                ('user_removegroups', models.BooleanField(default=False)),
                ('user_editposts', models.BooleanField(default=False)),
                ('user_removeposts', models.BooleanField(default=False)),
                ('user_banuser', models.BooleanField(default=False)),
                ('user_timebanuser', models.BooleanField(default=False)),
                ('user_unbanuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_authorizations',
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ManyToManyField(to='settings.Groups')),
                ('user_id', models.ManyToManyField(to='users.Users')),
            ],
            options={
                'db_table': 'user_groups',
            },
        ),
    ]
