# Generated by Django 3.0.2 on 2020-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroups',
            name='user_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='groups',
            table='authorized_groups',
        ),
        migrations.DeleteModel(
            name='UserAuthorization',
        ),
    ]
